// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiM7WIzQET7y8Aic_HnqbsPb2SQizWXrk',
    appId: '1:213725812876:web:cdc00a9d39e4cf605843a9',
    messagingSenderId: '213725812876',
    projectId: 'pennapps-narcan',
    authDomain: 'pennapps-narcan.firebaseapp.com',
    storageBucket: 'pennapps-narcan.appspot.com',
    measurementId: 'G-V6T02V4RWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_P5A9TiN2HrOVyKn4gVrC2nGoGnMEVZc',
    appId: '1:213725812876:android:b9afca9904fdc8815843a9',
    messagingSenderId: '213725812876',
    projectId: 'pennapps-narcan',
    storageBucket: 'pennapps-narcan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmOyv4APaj8WzJ7DOi2n6yE8TvrZzQo4o',
    appId: '1:213725812876:ios:050511d24d0bddb05843a9',
    messagingSenderId: '213725812876',
    projectId: 'pennapps-narcan',
    storageBucket: 'pennapps-narcan.appspot.com',
    iosBundleId: 'com.example.betterHomework',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmOyv4APaj8WzJ7DOi2n6yE8TvrZzQo4o',
    appId: '1:213725812876:ios:e03f66bbcfb27be45843a9',
    messagingSenderId: '213725812876',
    projectId: 'pennapps-narcan',
    storageBucket: 'pennapps-narcan.appspot.com',
    iosBundleId: 'com.example.betterHomework.RunnerTests',
  );
}
